spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdemo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  session:
    #关闭session
    store-type: none
server:
  port: 8888
security:
  basic:
    #关闭security false   登录
    enabled: true
#imooc.security.browser.loginPage = /demo-signIn.html
imooc:
  browser:
    loginPage: /demo-signIn.html
    loginType: REDIRECT


